version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - API_BASE_URL=http://server:8080
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: dotgh1@#
      MYSQL_DB: TutorBuddyDB
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dotgh1@#
      MYSQL_DATABASE: TutorBuddyDB
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  client_node_modules:
  server_node_modules:
